/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: '#10131a',
        primary: '#adc6ff',
        'on-primary': '#002e6a',
        'primary-container': '#4d8eff',
        'on-primary-container': '#00285d',
        'inverse-primary': '#005ac2',
        secondary: '#b9c8de',
        'on-secondary': '#233143',
        'secondary-container': '#39485a',
        'on-secondary-container': '#a7b6cc',
        tertiary: '#ffb786',
        'on-tertiary': '#502400',
        'tertiary-container': '#df7412',
        'on-tertiary-container': '#461f00',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        surface: '#10131a',
        'surface-dim': '#10131a',
        'surface-bright': '#363941',
        'surface-container-lowest': '#0b0e15',
        'surface-container-low': '#191b23',
        'surface-container': '#1d2027',
        'surface-container-high': '#272a31',
        'surface-container-highest': '#32353c',
        'on-surface': '#e1e2ec',
        'on-surface-variant': '#c2c6d6',
        'inverse-surface': '#e1e2ec',
        'inverse-on-surface': '#2e3038',
        outline: '#8c909f',
        'outline-variant': '#424754',
      },
      fontFamily: {
        sans: ["Montserrat-Regular", "sans-serif"],
        body: ["Montserrat-Regular", "sans-serif"],
      },
    },
  },
  plugins: [],
}
